BTL_DiDongViet/Models/News.cs
namespace BTL_DiDongViet.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class News
    {
        [Key]
        [Required(ErrorMessage = "Trường ID trống")]
        public long ID { get; set; }

        [StringLength(50)]
        [Display(Name = "Tiêu đề")]
        public string Title { get; set; }

        [Column(TypeName = "ntext")]
        [Display(Name = "Nội dung")]
        public string NewContent { get; set; }

        [StringLength(10)]
        [Display(Name = "Ảnh")]
        public string Image { get; set; }

        [StringLength(500)]
        [Display(Name = "Mô tả")]
        public string Description { get; set; }
        [Display(Name = "Ngày tạo")]
        public DateTime? CreatedDate { get; set; }
    }
}

BTL_DiDongViet/Controllers/InformationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


//Hiển thị thông tin liên hệ, chính sách khách hàng
namespace BTL_DiDongViet.Controllers
{
    public class InformationController : Controller
    {
        // GET: Information
        public ActionResult Contact()
        {
            return View();
        }

        public ActionResult Policy()
        {
            return View();
        }

        public ActionResult Gioithieu()
        {
            return View();
        }
    }
}

BTL_DiDongViet/Controllers/NewsController.cs
using BTL_DiDongViet.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList.Mvc;

//Phần controller tin tức của trang web
namespace BTL_DiDongViet.Controllers
{
    public class NewsController : Controller
    {
        // GET: News
        public DBDiDongViet db = new DBDiDongViet();
        public ActionResult News()
        {
            return View(db.News.ToList());
        }
        public ActionResult Display(int? page)
        {
            var news = db.News.Select(x => x);
            news = news.OrderBy(x => x.ID);
            int pageSize = 4;
            int pageNumber = (page ?? 1);
            return View(news.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Detail(long id)
        {
            var model = db.News.SingleOrDefault(x => x.ID == id);
            if (model == null)
            {
                return HttpNotFound();
            }
            ViewBag.Lst = db.News.Where(x => x.ID != id).ToList();
            return View(model);
        }

        public ActionResult Policy()
        {
            return View();
        }
        public ActionResult Gioithieu()
        {
            return View();
        }
        public ActionResult Lienhe()
        {
            return View();
        }
    }
}

BTL_DiDongViet/Views/News/Detail.cshtml
@model BTL_DiDongViet.Models.News

@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<style>
    a:hover {
        color: #be1e2d !important;
    }

    .trang {
        width: 75px;
        height: 45px;
        display: block;
    }

        .trang .pagination {
            font-size: 16px;
            background: white;
            display: flex;
            transform: translateX(1095px);
            height: 30px;
            padding: 8px;
            width: max-content;
        }

        .trang .active {
            display: block;
            margin-right: 14px;
            height: 15px;
        }

        .trang a {
            text-decoration: none;
            color: black;
        }

        .trang li {
            margin: 0 10px;
        }
</style>
<div class="main" style="padding-top: 0px;">
    <!-- Welcome Package Begin -->
    <div class="welcome-package-banner"
         data-current-src="https://cf.shopee.vn/file/d3fa706887cf34ddd491c8fc60e37d9f_xxhdpi"
         style="background-image: url(https://didongviet.vn/pub/media/mageplaza/bannerslider/banner/image/1/2/1280x80_3_.png); background-size: contain; background-repeat: no-repeat;">
    </div>
    <!-- Welcome Package End -->
    <div>
        <a href="/Category/Home" class="nav-link nav-arrow">Trang chủ</a>
        <a href="/News/Display" class="nav-link nav-arrow">Tin tức</a>
        <span class="nav-link">@Model.Title</span>
    </div>
    <!-- Section Below The Fold Begin -->
    <div class="section-below-the-fold" style="padding-bottom: 0;">
        <!-- Flash Sale Begin-->
        <div class="shopee-flash-sale-overview-carousel">
            <div class="shopee-header-section
                        shopee-header-section--simple">
                <div class="shopee-header-section__header">
                    <div class="shopee-header-section__header__title"
                         style=" padding: 16px 0;margin-right: 0">
                       
                    </div>
                </div>
                <div class="shopee-header-section__content">
                    <div class="image-carousel">
                        <div class="image-carousel__item-list-wrapper">
                            <div class="container" style="flex-direction: column">
                                <img style="object-fit: contain;" src="~/assets/img/NewsImage/@Model.Image" alt="">
                                <div class="container-right">
                                    <h2 style="margin-bottom: 4px;font-size: 24px">
                                        <a href="" style="text-decoration: none; ">@Model.Title</a>
                                    </h2>
                                    <div class="new-time">@Model.CreatedDate</div>
                                    <div class="new-desc">@Model.NewContent</div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
               
            </div>
        </div>
        <!-- Flash Sale End-->
        <!-- Skinny Banner Beign-->
        <div style="margin-top: 20px">
            <div class="shopee-skinny-banner__container">
                <a class="shopee-skinny-banner" href="" style="width: 610px;
                           height: 119px;
                           border-radius: 2px;">
                    <div class="reactJS-25r8I
                              shopee-skinny-banner__full-height">
                        <div style="background: url(https://cdn.didongviet.vn/pub/media/mageplaza/bannerslider/banner/image/a/i/airpod-3.jpg);
                                 background-size: cover;
                                 background-repeat: no-repeat;" class="shopee-skinny-banner__full-height
                                 reactJS_2GchKS"></div>
                    </div>
                </a>
            </div>
            <div class="shopee-skinny-banner__container">
                <a class="shopee-skinny-banner" href="" style="width: 610px;
                           height: 119px;
                           border-radius: 2px;">
                    <div class="reactJS-25r8I
                              shopee-skinny-banner__full-height">
                        <div class="shopee-skinny-banner__full-height
                                 reactJS_2GchKS" style="background-image: url(https://cdn.didongviet.vn/pub/media/mageplaza/bannerslider/banner/image/a/i/airpods-didongviet-banner-1.jpg);
                                 background-size: cover;
                                 background-repeat: no-repeat;"></div>
                    </div>
                </a>
            </div>
        </div>
        <!-- Skinny Banner End-->
        <!-- Section Below The Fold End -->
    </div>
</div>

BTL_DiDongViet/Views/News/Display.cshtml
@model PagedList.IPagedList<BTL_DiDongViet.Models.News>
@using PagedList;
@using PagedList.Mvc;


@{
    ViewBag.Title = "Display";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<style>
    a:hover {
        color: #be1e2d !important;
    }

    .trang {
        width: 75px;
        height: 45px;
        display: block;
    }

        .trang .pagination {
            font-size: 16px;
            background: white;
            display: flex;
            transform: translateX(1095px);
            height: 30px;
            padding: 8px;
            width: max-content;
        }

        .trang .active {
            display: block;
            margin-right: 14px;
            height: 15px;
        }
            .trang a {
                text-decoration: none;
                color: black;
            }
    .trang li {
        margin: 0 10px;
    }
</style>
<div class="main" style="padding-top: 0px;">
    <!-- Welcome Package Begin -->
    <div class="welcome-package-banner"
         data-current-src="https://cf.shopee.vn/file/d3fa706887cf34ddd491c8fc60e37d9f_xxhdpi"
         style="background-image: url(https://didongviet.vn/pub/media/mageplaza/bannerslider/banner/image/1/2/1280x80_3_.png); background-size: contain; background-repeat: no-repeat;">
    </div>
    <!-- Welcome Package End -->
    <div>
        <a href="/Category/Home" class="nav-link nav-arrow">Trang chủ</a>
        <span class="nav-link">Tin tức</span>
    </div>
    <!-- Section Below The Fold Begin -->
    <div class="section-below-the-fold" style="padding-bottom: 0;">
        <!-- Flash Sale Begin-->
        <div class="shopee-flash-sale-overview-carousel">
            <div class="shopee-header-section
                        shopee-header-section--simple">
                <div class="shopee-header-section__header">
                    <div class="shopee-header-section__header__title"
                         style=" padding: 16px 0;margin-right: 0">
                        Tin tức công nghệ
                    </div>
                </div>
                <div class="shopee-header-section__content">
                    @foreach (var item in Model)
                    {
                        string url = "Detail/" + item.ID;
                        string de = item.NewContent.Substring(0, 250);
                        <div class="image-carousel">
                            <div class="image-carousel__item-list-wrapper"
                                 style="margin-top: 16px;">
                                <div class="container">
                                    <img style="width: 300px; height: auto;object-fit: contain;"
                                         src="~/assets/img/NewsImage/@item.Image" alt="">
                                    <div class="container-right">
                                        <h2 style="margin-bottom: 4px;font-size: 24px">
                                            <a href="@url" class="news-links"
                                               style="text-decoration: none; color: black ">@item.Title</a>
                                        </h2>
                                        <div class="new-time">@item.CreatedDate</div>
                                        <div class="new-desc">@item.Description <span>
    <a href="@url">Xem thêm</a>
</span></div>
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                    }

                </div>
                <div class="trang">
                    <div class="danh-sach-bot">
                        @Html.PagedListPager(Model, page => Url.Action("Display", "News", new { page }))
                    </div>
                </div>
            </div>
        </div>
        <!-- Flash Sale End-->
        <!-- Skinny Banner Beign-->
        <div style="margin-top: 20px">
            <div class="shopee-skinny-banner__container">
                <a class="shopee-skinny-banner" href="" style="width: 610px;
                           height: 119px;
                           border-radius: 2px;">
                    <div class="reactJS-25r8I
                              shopee-skinny-banner__full-height">
                        <div style="background: url(https://cdn.didongviet.vn/pub/media/mageplaza/bannerslider/banner/image/a/i/airpod-3.jpg);
                                 background-size: cover;
                                 background-repeat: no-repeat;" class="shopee-skinny-banner__full-height
                                 reactJS_2GchKS"></div>
                    </div>
                </a>
            </div>
            <div class="shopee-skinny-banner__container">
                <a class="shopee-skinny-banner" href="" style="width: 610px;
                           height: 119px;
                           border-radius: 2px;">
                    <div class="reactJS-25r8I
                              shopee-skinny-banner__full-height">
                        <div class="shopee-skinny-banner__full-height
                                 reactJS_2GchKS" style="background-image: url(https://cdn.didongviet.vn/pub/media/mageplaza/bannerslider/banner/image/a/i/airpods-didongviet-banner-1.jpg);
                                 background-size: cover;
                                 background-repeat: no-repeat;"></div>
                    </div>
                </a>
            </div>
        </div>
        <!-- Skinny Banner End-->
        <!-- Section Below The Fold End -->
    </div>
</div>

BTL_DiDongViet/Views/News/News.cshtml
@{
    ViewBag.Title = "News";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="main" style="padding-top: 0px;">
    <!-- Welcome Package Begin -->
    <div class="welcome-package-banner" data-current-src="https://cf.shopee.vn/file/d3fa706887cf34ddd491c8fc60e37d9f_xxhdpi" style="background-image: url(https://didongviet.vn/pub/media/mageplaza/bannerslider/banner/image/1/2/1280x80_3_.png); background-size: contain; background-repeat: no-repeat;"></div>
    <!-- Welcome Package End -->
    <div>
        @Html.ActionLink("Trang chủ", "Contact", "Information", null, new { @class = "nav-link nav-arrow" })
        <span class="nav-link">Tin tức</span>
    </div>
    <!-- Section Below The Fold Begin -->
    <div class="section-below-the-fold" style="padding-bottom: 0;">
        <!-- Flash Sale Begin-->
        <div class="shopee-flash-sale-overview-carousel">
            <div class="shopee-header-section
                        shopee-header-section--simple">
                <div class="shopee-header-section__header">
                    <div class="shopee-header-section__header__title" style=" padding: 16px 0;margin-right: 0">
                        <div class="flash-sale-header-with-countdown-timer
                                 flash-sale-header-with-countdown-timer--undefined">
                            <div class="flash-sale-header-with-countdown-timer__wrapper
                                    flash-sale-header-with-countdown-timer__wrapper--undefined">
                                <div class="
                                       flash-sale-header-with-countdown-timer__header--vn">Tin tức công nghệ</div>
                                <div class="shopee-countdown-timer
                                       flash-sale-header-with-countdown-timer__countdown-timer">
                                    <div class="shopee-countdown-timer__number">
                                        <div class="shopee-countdown-timer__number__hexa"></div>
                                        <div class="shopee-countdown-timer__number__deca"></div>
                                    </div>
                                    <div class="shopee-countdown-timer__colon
                                          shopee-countdown-timer__colon--flashing-off">
                                        <div class="colon-dot__wrapper">
                                            <span class="colon-dot"></span>
                                        </div>
                                        <div class="colon-dot__wrapper">
                                            <span class="colon-dot"></span>
                                        </div>
                                    </div>
                                    <div class="shopee-countdown-timer__number"></div>
                                    <div class="shopee-countdown-timer__colon
                                          shopee-countdown-timer__colon--flashing-off"></div>
                                    <div class="shopee-countdown-timer__number"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- <a href="/flash_sale?promotionId=2026713624" class="shopee-header-section__header-link"> <button class="shopee-button-no-outline"> Xem thêm&ensp; <svg enable-background="new 0 0 11 11" viewbox="0 0 11 11" x="0" y="0" class="shopee-svg-icon icon-arrow-right"> <path d="m2.5 11c .1 0 .2 0
                    .3-.1l6-5c .1-.1.2-.3.2-.4s-.1-.3-.2-.4l-6-5c-.2-.2-.5-.1-.7.1s-.1.5.1.7l5.5 4.6-5.5 4.6c-.2.2-.2.5-.1.7.1.1.3.2.4.2z"></path> </svg> </button> </a> -->
                </div>
                <div class="shopee-header-section__content">
                    <div class="image-carousel">
                        <div class="image-carousel__item-list-wrapper">
                            <div class="container" style="flex-direction: column">
                                <img style="object-fit: contain;" src="https://didongviet.vn/tin-tuc/wp-content/uploads/2021/12/so-sanh-ipad-mini-5-va-ipad-gen-8-didongviet.jpg" alt="">
                                <div class="container-right">
                                    <h2 style="margin-bottom: 4px;font-size: 24px">
                                        <a href="" style="text-decoration: none; ">Top 7 phần mềm miễn phí tiện lợi dành cho laptop chơi game</a>
                                    </h2>
                                    <div class="new-time">10/12/2021</div>
                                    <div class="new-desc">
                                        iPad mini 5 và iPad Gen 8 tuy ra mắt cách nhăm 1 năm nhưng lại sở hữu nhiều thông số có phần khá tương đồng. Tuy nhiên, mức giá bán của chúng lại chênh lệch nhau, khiến cho không ít người dùng băn khoăn. Hãy cùng mình so sánh iPad mini 5 và iPad Gen 8 để xem đâu là chiếc tablet
                                        đáng để sở hữu hơn. So sánh iPad mini 5 và iPad Gen 8: Sự khác biệt nằm ở đâu? Dòng iPad giá rẻ thông thường cùng với dòng iPad mini được xem là những phiên bản máy tính bảng Apple có kích thước nhỏ nhất đi kèm với giá bán cực phải chăng. Vì vậy, chúng cũng sở hữu khá nhiều điểm chung. Tuy nhiên,
                                        nếu chúng ta xem xét thật kỹ càng bên trong từng yếu tố thì vẫn có thể thấy được điểm đặc trưng riêng của mỗi dòng. Trong quá khứ, việc Apple tung ra chiếc iPad Gen 8 sau iPad mini 5 với mức giá thấp hơn đã làm cho nhiều iFan đặt nên câu hỏi liệu nhà sản xuất có làm gì sai hay không. Nhiều người
                                        dùng cũng không biết rằng vì sao họ lại đặt giá bán của các thiết bị của mình mâu thuẫn đến như vậy. Cùng xem qua bài so sánh iPad Gen 8 và mini 5 phía dưới để tìm ra câu trả lời chính xác nhất cho bài toán hóc búa này. 1. Giá bán hiện tại iPad Gen 8 là một siêu phẩm đến từ Apple dù đã ra mắt khá
                                        lâu nhưng vẫn còn giữ được độ hot trong những ngày trở lại đây. Tại thời điểm ra mắt, thiết bị được lên kệ với mức giá 329 USD (khoảng 7,5 triệu đồng). Đây cũng được xem là tablet có giá thuộc top mềm nhất trong những sản phẩm Apple đã cho ra mắt. Nhưng ngạc nhiên thay, chiếc iPad mini 5 được bán
                                        với giá 399 USD (khoảng 9,1 triệu). Đó chính là một điều khá khó hiểu mà bấy lâu nay người dùng đang đặt một dấu hỏi lớn cho Táo khuyết. Phần cứng có trên hai thiết bị này là khá tương tự nhau và iPad mini 5 còn được công bố sớm hơn 1 năm nhưng mức giá của nó lại cao hơn so với iPad Gen 8.
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Flash Sale End-->
        <!-- Skinny Banner Beign-->
        <div style="margin-top: 20px">
            <div class="shopee-skinny-banner__container">
                <a class="shopee-skinny-banner" href="" style="width: 610px;
                           height: 119px;
                           border-radius: 2px;">
                    <div class="reactJS-25r8I
                              shopee-skinny-banner__full-height">
                        <div style="background: url(https://cdn.didongviet.vn/pub/media/mageplaza/bannerslider/banner/image/a/i/airpod-3.jpg);
                                 background-size: cover;
                                 background-repeat: no-repeat;" class="shopee-skinny-banner__full-height
                                 reactJS_2GchKS"></div>
                    </div>
                </a>
            </div>
            <div class="shopee-skinny-banner__container">
                <a class="shopee-skinny-banner" href="" style="width: 610px;
                           height: 119px;
                           border-radius: 2px;">
                    <div class="reactJS-25r8I
                              shopee-skinny-banner__full-height">
                        <div class="shopee-skinny-banner__full-height
                                 reactJS_2GchKS" style="background-image: url(https://cdn.didongviet.vn/pub/media/mageplaza/bannerslider/banner/image/a/i/airpods-didongviet-banner-1.jpg);
                                 background-size: cover;
                                 background-repeat: no-repeat;"></div>
                    </div>
                </a>
            </div>
        </div>
        <!-- Skinny Banner End-->
        <!-- Section Below The Fold End -->
    </div>
</div>