BTL_DiDongViet/Models/Product.cs
namespace BTL_DiDongViet.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            Feedbacks = new HashSet<Feedback>();
            OrderDetails = new HashSet<OrderDetail>();
        }

        public long ID { get; set; }

        [Required]
        [StringLength(250)]
        public string ProductName { get; set; }

        public long? CategoryID { get; set; }

        [StringLength(50)]
        public string Storage { get; set; }

        [Column(TypeName = "money")]
        public decimal Price { get; set; }

        [Required]
        [StringLength(50)]
        public string Color { get; set; }

        public decimal? Sale { get; set; }

        public long Quantity { get; set; }

        [Required]
        [StringLength(50)]
        public string Image { get; set; }

        [StringLength(250)]
        public string Description { get; set; }

        [StringLength(250)]
        public string Sets { get; set; }

        [StringLength(250)]
        public string Insurance { get; set; }

        public long? NumberOfPurchases { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback> Feedbacks { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }

        public virtual ProductCategory ProductCategory { get; set; }
    }
}

BTL_DiDongViet/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BTL_DiDongViet.Models;
using PagedList;

namespace BTL_DiDongViet.Controllers
{
    public class CategoryController : Controller
    {
        DBDiDongViet db = new DBDiDongViet();
        // GET: Category
        public ActionResult Home(int? userID)
        {
            HomeViewModel viewModel = new HomeViewModel();
            viewModel.Product = db.Products.ToList();
            viewModel.Category = db.ProductCategory.ToList();
            return View(viewModel);
        }

        public ActionResult Category(int? categoryID, int? page, string name = "default")
        {
            HomeViewModel viewModel = new HomeViewModel();
            if (categoryID != null)
            {
                var product = db.Products.ToList().FindAll(p => p.CategoryID == categoryID);
                var categoty = db.ProductCategory.Find(categoryID);
                viewModel.Product = product;
                viewModel.Category.Add(categoty);
            }
            else
            {
                if(name.Equals("default"))
                {
                    return View("Home");
                }
                else
                {            
                    var categoty = db.ProductCategory.FirstOrDefault(c => c.Name == name);
                    var product = db.Products.ToList().FindAll(p => p.CategoryID == categoty.ID);
                    viewModel.Product = product;
                    viewModel.Category.Add(categoty);
                }
            }
            return View(viewModel);
        }
    }
}

BTL_DiDongViet/Controllers/OrderDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BTL_DiDongViet.Models;
using BTL_DiDongViet.Common;

namespace BTL_DiDongViet.Controllers
{
    public class OrderDetailController : Controller
    {
        DBDiDongViet db = new DBDiDongViet();

        public CartViewModel layGioHang(int userID)
        {
                var order = db.Order.ToList().Find(o => o.UserID == userID);
           
                List<OrderDetail> orderDetail = db.OrderDetail.ToList().FindAll(o => o.OrderID == order.ID);
                List<Products> productList = new List<Products>();
                foreach (var item in orderDetail)
                {
                    var prod = db.Products.Find(item.ProductID);
                    productList.Add(prod);
                }
                CartViewModel viewModel = new CartViewModel();
                viewModel.order = orderDetail;
                viewModel.product = productList;
            return viewModel;
        }

        public ActionResult Cart()
        {
            if(Session[CommonConstants.CLIENT_SESSION] != null)
            {
                var user = (UserLogin)Session[CommonConstants.CLIENT_SESSION];
                CartViewModel viewModel =  layGioHang((int)user.UserID);
                return View(viewModel);
            }
            return RedirectToAction("LoginIndex", "Users");
        }
        public ActionResult XoaGioHang(int? productID)
        {
            var user = (UserLogin)Session[CommonConstants.CLIENT_SESSION];
            if(user != null)
            {
                if (productID != null)
                {
                    var order = db.Order.ToList().Find(o => o.UserID == user.UserID);
                    List<OrderDetail> orderDetail = db.OrderDetail.ToList().FindAll(o => o.OrderID == order.ID);
                    if (orderDetail != null)
                    {
                        orderDetail.RemoveAll(n => n.ProductID != productID);
                        foreach(var item in orderDetail)
                        {
                            db.OrderDetail.Remove(item);
                        }
                        db.SaveChanges();
                        return RedirectToAction("Cart");
                    }
                    if (orderDetail.Count == 0)
                    {
                        return RedirectToAction("Index", "Product");
                    }
                }

                return RedirectToAction("Cart");
            }
            return RedirectToAction("LoginIndex", "Users");
        }

        public ActionResult ChinhSuaSoLuong(int? productID, string act = "default")
        {
            if(Session[CommonConstants.CLIENT_SESSION] != null)
            {
                if(productID == null || act.Equals("default"))
                {
                    return RedirectToAction("Cart");
                }
                var user = (UserLogin)Session[CommonConstants.CLIENT_SESSION];
                var order = db.Order.ToList().Find(o => o.UserID == user.UserID);
                if (act.Equals("add"))
                {
                    db.OrderDetail.ToList().Find(o => o.OrderID == order.ID && o.ProductID == productID).Quantity++;
                }
                else
                {
                    db.OrderDetail.ToList().Find(o => o.OrderID == order.ID && o.ProductID == productID).Quantity--;
                    if (db.OrderDetail.ToList().Find(o => o.OrderID == order.ID && o.ProductID == productID).Quantity == 0)
                    {
                        XoaGioHang((int)productID);
                    }
                }
                db.SaveChanges();
                return RedirectToAction("Cart");
            }

            return RedirectToAction("LoginIndex", "Users");
        }

        public ActionResult AddProductToCart(int? productID)
        {
            if (Session[CommonConstants.CLIENT_SESSION] != null && productID != null)
            {
                var user = (UserLogin)Session[CommonConstants.CLIENT_SESSION];
                var product = db.Products.ToList().Find(p => p.ID == productID);
                var order = db.Order.ToList().Find(o => o.UserID == user.UserID);
                OrderDetail orderDetail = new OrderDetail();
                orderDetail.ProductID = product.ID;
                orderDetail.OrderID = order.ID;
                orderDetail.Quantity = 1;
                db.OrderDetail.Add(orderDetail);
                db.SaveChanges();
                return RedirectToAction("Detail", "Products", new { id = productID });
            }
            else
            {
                return RedirectToAction("LoginIndex", "Users");
            }
        }
    }
}

BTL_DiDongViet/Controllers/ProductsController.cs
using BTL_DiDongViet.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList.Mvc;
using BTL_DiDongViet.Models.Dao;
using BTL_DiDongViet.Common;
using System.Data;
using System.Data.Entity;
using System.Net;
using PagedList;



namespace BTL_DiDongViet.Controllers
{
    public class ProductsController : Controller
    {

        public DBDiDongViet db = new DBDiDongViet();

        // GET: Products
        public ActionResult Detail(long? id)
        {
            if(id == null)
            {
                return RedirectToAction("Home", "Category");
            }
            else
            {
                long id2 = (long)id;
                var model = db.Products.SingleOrDefault(x => x.ID == id);
                if (model == null)
                {
                    return HttpNotFound();
                }
                FeedbackModel Feedback = new FeedbackModel();
                ViewBag.ListFB = Feedback.ListFeedback(11,id2);
                ViewBag.Lst = db.Products.Where(x => x.ID != id).ToList();
                return View(model);
            }

        }

        public ActionResult AddFeedback(string id, string feedback)
        {
            var user = (UserLogin)Session[CommonConstants.CLIENT_SESSION];
            if (user != null || id == null || feedback != null)
            {
                DateTime dateTime = DateTime.Now;
                Feedback feedback1 = new Feedback();
                feedback1.ProductID = int.Parse(id);
                feedback1.UserID = user.UserID;
                feedback1.FBContent = feedback;
                feedback1.CreatedDate = dateTime;
                db.Feedback.Add(feedback1);
                db.SaveChanges();
                return RedirectToAction("Detail", "Products", new { id = id });
            }
            else
            {
                return RedirectToAction("Home", "Category");
            }

        }

        public ActionResult Index(string sortOrder, string searchString, string currentFilter, int? page)
        {
            ViewBag.CurentSort = sortOrder;
            ViewBag.XepTheoTen = string.IsNullOrEmpty(sortOrder) ? "ten_desc" : "";
            ViewBag.XepTheoGia = sortOrder == "gia" ? "gia_desc" : "gia";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            var products = db.Products.Include(p => p.ProductCategory);
            if (!string.IsNullOrEmpty(searchString))
            {
                products = products.Where(u => u.ProductName.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "ten_desc":
                    products = products.OrderByDescending(s => s.ProductName);
                    break;
                case "gia":
                    products = products.OrderBy(s => s.Price);
                    break;
                case "gia_desc":
                    products = products.OrderByDescending(s => s.Price);
                    break;
                default:
                    products = products.OrderBy(s => s.ProductName);
                    break;
            }
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(products.ToPagedList(pageNumber, pageSize));
        }

        // GET: Products1/Create
        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.ProductCategory, "ID", "Name");
            return View();
        }

        // POST: Products1/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,ProductName,CategoryID,Storage,Price,Color,Sale,Quantity,Image,Description,Sets,Insurance,NumberOfPurchases")] Products products)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    products.Image = "";
                    var f = Request.Files["ImageFile"];
                    if(f != null && f.ContentLength > 0){
                        string filename = System.IO.Path.GetFileName(f.FileName);
                        string uploadPath = Server.MapPath("~/assets/img/ProductsImage" + filename);
                        f.SaveAs(uploadPath);
                        products.Image = filename;
                    }
                    db.Products.Add(products);
                    db.SaveChanges();
                }
                ViewBag.Err = null;
                ViewBag.CategoryID = new SelectList(db.ProductCategory, "ID", "Name", products.CategoryID);
                return RedirectToAction("Index");
            }
            catch(Exception e)
            {
                ViewBag.Err = "Lỗi" + e.Message;
                return View(products);
            }
        }

        // GET: Products1/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Products products = db.Products.Find(id);
            if (products == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryID = new SelectList(db.ProductCategory, "ID", "Name", products.CategoryID);
            return View(products);
        }

        // POST: Products1/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,ProductName,CategoryID,Storage,Price,Color,Sale,Quantity,Image,Description,Sets,Insurance,NumberOfPurchases")] Products products)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    products.Image = "";
                    var f = Request.Files["ImageFile"];
                    if (f != null && f.ContentLength > 0)
                    {
                        string filename = System.IO.Path.GetFileName(f.FileName);
                        string uploadPath = Server.MapPath("~/assets/img/ProductsImage" + filename);
                        f.SaveAs(uploadPath);
                        products.Image = filename;
                    }
                    db.Entry(products).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                ViewBag.CategoryID = new SelectList(db.ProductCategory, "ID", "Name", products.CategoryID);
                return View("Index");
            }catch(Exception e)
            {
                ViewBag.Err1 = "Lỗi" + e.Message;
                return View(products);
            }

        }

        // GET: Products1/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Products products = db.Products.Find(id);
            if (products == null)
            {
                return HttpNotFound();
            }
            return View(products);
        }

        // POST: Products1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            Products products = db.Products.Find(id);
            db.Products.Remove(products);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }

}

BTL_DiDongViet/Views/Products/Create.cshtml
@model BTL_DiDongViet.Models.Products

@{
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
</head>
<body>
    @using (Html.BeginForm("Create", "Products", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.CategoryID, "CategoryID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("CategoryID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Storage, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Storage, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Storage, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Sale, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Sale, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Sale, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                </div>
            </div>
            <script>
                var loadFile = function (event) {
                    var image = document.getElementById('output');
                    image.src = URL.createObjectURL(event.target.files[0]);
                }
            </script>
            <div class="form-group">
                @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                   <img id="output" class="img-rounded" alt="Ảnh" width="180" height="200" src="~/assets/img/ProductsImage/h0.png"/>
                    <p><label for="ufile" style="cursor:pointer">Chọn file ảnh</label></p>
                    <input name="ImgaeFile" id="ufile" type="file" style="display:none" onchange="loadFile(event)"/>
                </div>
            </div>
            @if(ViewBag.Err != null)
                {
                    <br />
                    <div class="alert alert-danger" role="alert" >@ViewBag.Err</div>
                }
            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Sets, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Sets, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Sets, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Insurance, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Insurance, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Insurance, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.NumberOfPurchases, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NumberOfPurchases, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NumberOfPurchases, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Trở lại danh sách", "Index")
    </div>
</body>
</html>

BTL_DiDongViet/Views/Products/Delete.cshtml
@model BTL_DiDongViet.Models.Products

@{
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Bạn có chắc muốn xóa sản phẩm  @Html.DisplayFor(model => model.ProductName)?</h3>
    <div> 
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Xóa" class="btn btn-default" />
                @Html.ActionLink("Trở về danh sách", "Index")
            </div>
        }
    </div>
</body>
</html>

BTL_DiDongViet/Views/Products/Detail.cshtml
@model BTL_DiDongViet.Models.Products
@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var ListFB = (List<BTL_DiDongViet.ViewModel.Feedback>)ViewBag.ListFB;
}
<div class="main pd-top-0">
    <!-- Welcome Package Begin -->
    <div class="welcome-package-banner" data-current-src="https://cf.shopee.vn/file/d3fa706887cf34ddd491c8fc60e37d9f_xxhdpi" style="background-image: url(https://didongviet.vn/pub/media/mageplaza/bannerslider/banner/image/1/2/1280x80_3_.png); background-size: contain; background-repeat: no-repeat;"></div>
    <!-- Welcome Package End -->
    <!-- Nav Tag Begin -->
    <div>
        <a href="@Url.Action("Home", "Category")" class="nav-link nav-arrow">Trang chủ</a>
        <a class="nav-link">@Model.ProductName</a>
    </div>
    <!-- Nav Tag End-->
    <!-- Product Begin-->
    <div class="product-wrapper">
        <div class="product-wrapper-left">
            <div style="max-width: 356px;">
                <img src="~/assets/img/ProductsImage/@Model.Image" alt="">
                <div style="padding: 16px; line-height: 24px;">
                    @Model.Description
                </div>
            </div>
            <div style="display: inline-block; width: 830px;">
                <div class="product-title">

                    @Model.ProductName

                </div>
                <div class="product-info" style="margin-top: 8px;">
                    <div class="product-ram">@Model.Storage</div>
                    <div class="product-price">@Model.Price ₫</div>
                </div>
                <div class="product-color">@Model.Color</div>
                <div class="product-status">
                    <i class="fas fa-map-marker-alt margin-right: 0.4rem;"></i>
                    @if (@Model.Quantity > 0)
                    {
                        <span>Hiện đang còn hàng</span>
                    }
                    else
                    {
                        <span>Hiện đã hết hàng</span>
                    }
                </div>
                <div class="product-giaohang" style="padding: 12px; font-size: 16px; "> <i class="fas fa-tag" style="margin-right: 8px;"></i>@Model.Sale % GIẢM</div>
                @if (@Model.Quantity > 0)
                {
                    <div class="product-dathang" type="submit"><a href="@Url.Action("AddProductToCart", "OrderDetail", new { productID = Model.ID })" style="text-decoration:none; color: white;">THÊM VÀO GIỎ HÀNG</a></div>

                }
                else
                {
                    <button class="product-dathang" type="submit" disabled>THÊM VÀO GIỎ HÀNG</button>

                }
            </div>
        </div>
        <div class="product-wrapper-right">
            <div class="bosanpham">
                <i class="fas fa-archive"></i>Bộ sản phẩm
                <div class="desc">@Model.Sets</div>
            </div>
            <div class="baohanh">
                <i class="fas fa-clipboard-check"></i>Bảo hành
                <div class="desc">
                    @Model.Insurance
                </div>
            </div>
        </div>
    </div>
    <div class="product-wrapper-left feedback-container">
        <!-- FeedBack Begin-->
        <header>
            Feedback về sản phẩm
        </header>
        @using (Html.BeginForm("AddFeedback", "Products", new { id = Model.ID }))
        {
            <div style="width: 400px;">
                <textarea onclick="" name="feedback" class="field-required" placeholder="Hãy thêm đánh giá về sản phẩm..." id="review_field" cols="5" rows="3" data-validate="{required:true}"></textarea>
                <input class="product-dathang fb-button"  style="width:120px;" type="submit" value="Gửi nhận xét"/>
            </div>
        }

        <!-- FeedBack End-->
    </div>

    @foreach(var item in ListFB)
    {
        
<div class="product-wrapper-left feedback-container"
     style="display: flex; flex-direction: column; line-height: 26px;">
    <!-- FeedBack Begin-->
    <header>
        <i class="fas fa-user" style="margin-right: 8px;"></i>@item.UserName
    </header>

    <div>@item.FBContent</div>
    <div style="color:#ccc;">@item.CreatedDate</div>
    <!-- FeedBack End-->
</div>

    }
    
    <!-- Product End-->
</div>